### ISSUE TITLE
compile to implementation

### ISSUE THREAD

**Issue by guyluz11** [haksist/DropdownTextView#4]
Android change compile to implementation
Log: "'compile' is obsolete and has been replaced with 'implementation'"
In the ReadMe file: 
Download

Gradle:

compile 'com.github.hakobast:dropdown-textview:0.2'

Need to be change to:
Download

Gradle:

implementation 'com.github.hakobast:dropdown-textview:0.2'

**Comment by hakobast** [comment]
Fixed. Thanks!
