### ISSUE TITLE
Title max lines

### ISSUE THREAD

**Issue by pjlbfr** [haksist/DropdownTextView#8]
please add a new method "setTitleMaxLines", because when I set a long text in the header, part of the text is hidden.

And in kotlin you don't need findViewById. You can simply use the element id from xml

**Comment by hakobast** [comment]
Hi currently DropdownTextView has getTitleTextView() function which you can use to get title text view to make your desired changes. About findViewById it is available with gradle's kotlin-android-extions plugin which i'm currently didn't use.
